services:
  nest-app:
    build:
      context: ./email-analyzer
      dockerfile: Dockerfile
    image: email-analyzer:latest
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/e-mail_analyzer?schema=public
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e-mail_analyzer
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"

networks:
  app-net:
    driver: bridge

volumes:
  pgdata: